### PR TITLE
added Lloyd's relaxation capability

### PR DESCRIPTION
**Pull request by LeonFedotov**
Hey, is this still the active repo? 
I needed some "chill" voronoi so iv'e added the relaxation from the demo of the libs you are using http://www.raymondhill.net/voronoi/rhill-voronoi-demo5.html 
41321352_2111500258882918_7155172277808847915_n

### CODE REVIEW

**Comment by hanskellner** [comment]
Hey @LeonFedotov - Thanks for the update.  Yes, this script is still alive.  Not sure why I didn't get a notification for this request.  Will take a look.

**Comment by LeonFedotov** [comment]
Cool, ive used mixed js style but i can just refactor ecerything into es6... 🙏😇

**Comment by LeonFedotov** [comment]
@hanskellner hey so im willing to write this in the current version of the - what i did was to paste my result from editing the code thats inside the addon on my install, what would you prefer done?

**Comment by hanskellner** [comment]
Hi @LeonFedotov - Sorry for the delay, I'm returning from traveling and will be able to get to it this week.

**Comment by hanskellner** [comment]
HI @LeonFedotov - Changes look great.  But there's an issue with Fusion and adding a button to the UI.  Fails in the Preview UI and is also randomly failing in the old UI.  I'm working to figure out how to fix or a workaround.  Thx.

**Comment by LeonFedotov** [comment]
@hanskellner cool :)
this version works for me as is, 
also i would love to add the ability to append the generated curves to the current sketch in edit instead of creating a new sketch.
let me know if you want to do some pair coding, ive been building editors at WIX for a while so i get the architecture.
maybe you can explain your bug a little, do you have a reproduction example that i can try debugging? 
cheers!

**Comment by hanskellner** [comment]
@LeonFedotov 
> i would love to add the ability to append the generated curves to the current sketch in edit instead of creating a new sketch.

Yes, a wish list of mine.  And when doing so, be able to specify a point to insert the curves.

> let me know if you want to do some pair coding

I'd be up for that.

> maybe you can explain your bug a little, do you have a reproduction example that i can try debugging?

I'm in contact with the developers and they are addressing the issue (and saving us time).  Part of the problem is the Preview UI and changes to the API.  Will post an update when I learn more.

**Pull request merged**
